// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PodiumService.proto

package com.smartclassroom.service3;

public interface IODeviceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IODeviceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deviceName = 1;</code>
   */
  java.lang.String getDeviceName();
  /**
   * <code>string deviceName = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceNameBytes();
}
