// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PodiumService.proto

package com.smartclassroom.service3;

public interface IODeviceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IODeviceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deviceStatus = 1;</code>
   */
  java.lang.String getDeviceStatus();
  /**
   * <code>string deviceStatus = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceStatusBytes();
}
