// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PodiumService.proto

package com.smartclassroom.service3;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string teacherID = 1;</code>
   */
  java.lang.String getTeacherID();
  /**
   * <code>string teacherID = 1;</code>
   */
  com.google.protobuf.ByteString
      getTeacherIDBytes();

  /**
   * <code>string passCode = 2;</code>
   */
  java.lang.String getPassCode();
  /**
   * <code>string passCode = 2;</code>
   */
  com.google.protobuf.ByteString
      getPassCodeBytes();
}
