// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PodiumService.proto

package com.smartclassroom.service3;

public final class PodiumService {
  private PodiumService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProjectorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProjectorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProjectorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ProjectorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IODeviceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IODeviceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IODeviceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IODeviceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023PodiumService.proto\"3\n\014LoginRequest\022\021\n" +
      "\tteacherID\030\001 \001(\t\022\020\n\010passCode\030\002 \001(\t\" \n\rLo" +
      "ginResponse\022\017\n\007message\030\001 \001(\t\":\n\020Projecto" +
      "rRequest\022\023\n\013projectorId\030\001 \001(\t\022\021\n\taccessP" +
      "in\030\002 \001(\t\"#\n\021ProjectorResponse\022\016\n\006status\030" +
      "\001 \001(\t\"%\n\017IODeviceRequest\022\022\n\ndeviceName\030\001" +
      " \001(\t\"(\n\020IODeviceResponse\022\024\n\014deviceStatus" +
      "\030\001 \001(\t2\272\001\n\rPodiumControl\022.\n\013PodiumLogin\022" +
      "\r.LoginRequest\032\016.LoginResponse\"\000\022?\n\024Proj" +
      "ectorIntegration\022\021.ProjectorRequest\032\022.Pr" +
      "ojectorResponse\"\000\0228\n\013IOInterface\022\020.IODev" +
      "iceRequest\032\021.IODeviceResponse\"\000(\0010\001B\037\n\033c" +
      "om.smartclassroom.service3P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginRequest_descriptor,
        new java.lang.String[] { "TeacherID", "PassCode", });
    internal_static_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LoginResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_ProjectorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ProjectorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProjectorRequest_descriptor,
        new java.lang.String[] { "ProjectorId", "AccessPin", });
    internal_static_ProjectorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ProjectorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ProjectorResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_IODeviceRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_IODeviceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IODeviceRequest_descriptor,
        new java.lang.String[] { "DeviceName", });
    internal_static_IODeviceResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_IODeviceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IODeviceResponse_descriptor,
        new java.lang.String[] { "DeviceStatus", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
