// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PodiumService.proto

package com.smartclassroom.service3;

public interface ProjectorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProjectorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string projectorId = 1;</code>
   */
  java.lang.String getProjectorId();
  /**
   * <code>string projectorId = 1;</code>
   */
  com.google.protobuf.ByteString
      getProjectorIdBytes();

  /**
   * <code>string accessPin = 2;</code>
   */
  java.lang.String getAccessPin();
  /**
   * <code>string accessPin = 2;</code>
   */
  com.google.protobuf.ByteString
      getAccessPinBytes();
}
