// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AssignmentService.proto

package com.smartclassroom.service2;

public final class AssignmentService {
  private AssignmentService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DetailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DetailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DetailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DetailResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubmitRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubmitRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SubmitResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SubmitResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReminderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReminderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReminderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReminderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027AssignmentService.proto\"$\n\rDetailReque" +
      "st\022\023\n\013subjectName\030\001 \001(\t\"R\n\016DetailRespons" +
      "e\022\024\n\014assignmentNo\030\001 \001(\t\022\031\n\021assignmentDet" +
      "ails\030\002 \001(\t\022\017\n\007dueDate\030\003 \001(\t\"a\n\rSubmitReq" +
      "uest\022\023\n\013subjectName\030\001 \001(\t\022\022\n\nassignment\030" +
      "\002 \001(\t\022\022\n\nattachment\030\003 \001(\t\022\023\n\013currentDate" +
      "\030\004 \001(\t\" \n\016SubmitResponse\022\016\n\006status\030\001 \003(\t" +
      "\"\"\n\017ReminderRequest\022\017\n\007subject\030\001 \001(\t\"$\n\020" +
      "ReminderResponse\022\020\n\010reminder\030\001 \001(\t2\313\001\n\024A" +
      "ssignmentSubmission\0225\n\020AssignmentDetail\022" +
      "\016.DetailRequest\032\017.DetailResponse\"\000\022;\n\024As" +
      "signmentSubmission\022\016.SubmitRequest\032\017.Sub" +
      "mitResponse\"\000(\001\022?\n\022AssignmentReminder\022\020." +
      "ReminderRequest\032\021.ReminderResponse\"\000(\0010\001" +
      "B\037\n\033com.smartclassroom.service2P\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_DetailRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DetailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DetailRequest_descriptor,
        new java.lang.String[] { "SubjectName", });
    internal_static_DetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DetailResponse_descriptor,
        new java.lang.String[] { "AssignmentNo", "AssignmentDetails", "DueDate", });
    internal_static_SubmitRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SubmitRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubmitRequest_descriptor,
        new java.lang.String[] { "SubjectName", "Assignment", "Attachment", "CurrentDate", });
    internal_static_SubmitResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SubmitResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SubmitResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_ReminderRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ReminderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReminderRequest_descriptor,
        new java.lang.String[] { "Subject", });
    internal_static_ReminderResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ReminderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReminderResponse_descriptor,
        new java.lang.String[] { "Reminder", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
