// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AssignmentService.proto

package com.smartclassroom.service2;

public interface DetailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DetailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string subjectName = 1;</code>
   */
  java.lang.String getSubjectName();
  /**
   * <code>string subjectName = 1;</code>
   */
  com.google.protobuf.ByteString
      getSubjectNameBytes();
}
