// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AssignmentService.proto

package com.smartclassroom.service2;

public interface DetailResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DetailResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string assignmentNo = 1;</code>
   */
  java.lang.String getAssignmentNo();
  /**
   * <code>string assignmentNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getAssignmentNoBytes();

  /**
   * <code>string assignmentDetails = 2;</code>
   */
  java.lang.String getAssignmentDetails();
  /**
   * <code>string assignmentDetails = 2;</code>
   */
  com.google.protobuf.ByteString
      getAssignmentDetailsBytes();

  /**
   * <code>string dueDate = 3;</code>
   */
  java.lang.String getDueDate();
  /**
   * <code>string dueDate = 3;</code>
   */
  com.google.protobuf.ByteString
      getDueDateBytes();
}
