// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AssignmentService.proto

package com.smartclassroom.service2;

/**
 * Protobuf type {@code DetailResponse}
 */
public  final class DetailResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:DetailResponse)
    DetailResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DetailResponse.newBuilder() to construct.
  private DetailResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DetailResponse() {
    assignmentNo_ = "";
    assignmentDetails_ = "";
    dueDate_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DetailResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            assignmentNo_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            assignmentDetails_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            dueDate_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smartclassroom.service2.AssignmentService.internal_static_DetailResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smartclassroom.service2.AssignmentService.internal_static_DetailResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smartclassroom.service2.DetailResponse.class, com.smartclassroom.service2.DetailResponse.Builder.class);
  }

  public static final int ASSIGNMENTNO_FIELD_NUMBER = 1;
  private volatile java.lang.Object assignmentNo_;
  /**
   * <code>string assignmentNo = 1;</code>
   */
  public java.lang.String getAssignmentNo() {
    java.lang.Object ref = assignmentNo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assignmentNo_ = s;
      return s;
    }
  }
  /**
   * <code>string assignmentNo = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAssignmentNoBytes() {
    java.lang.Object ref = assignmentNo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assignmentNo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSIGNMENTDETAILS_FIELD_NUMBER = 2;
  private volatile java.lang.Object assignmentDetails_;
  /**
   * <code>string assignmentDetails = 2;</code>
   */
  public java.lang.String getAssignmentDetails() {
    java.lang.Object ref = assignmentDetails_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assignmentDetails_ = s;
      return s;
    }
  }
  /**
   * <code>string assignmentDetails = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAssignmentDetailsBytes() {
    java.lang.Object ref = assignmentDetails_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assignmentDetails_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DUEDATE_FIELD_NUMBER = 3;
  private volatile java.lang.Object dueDate_;
  /**
   * <code>string dueDate = 3;</code>
   */
  public java.lang.String getDueDate() {
    java.lang.Object ref = dueDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dueDate_ = s;
      return s;
    }
  }
  /**
   * <code>string dueDate = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDueDateBytes() {
    java.lang.Object ref = dueDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dueDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAssignmentNoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, assignmentNo_);
    }
    if (!getAssignmentDetailsBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, assignmentDetails_);
    }
    if (!getDueDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dueDate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAssignmentNoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, assignmentNo_);
    }
    if (!getAssignmentDetailsBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, assignmentDetails_);
    }
    if (!getDueDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dueDate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smartclassroom.service2.DetailResponse)) {
      return super.equals(obj);
    }
    com.smartclassroom.service2.DetailResponse other = (com.smartclassroom.service2.DetailResponse) obj;

    boolean result = true;
    result = result && getAssignmentNo()
        .equals(other.getAssignmentNo());
    result = result && getAssignmentDetails()
        .equals(other.getAssignmentDetails());
    result = result && getDueDate()
        .equals(other.getDueDate());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ASSIGNMENTNO_FIELD_NUMBER;
    hash = (53 * hash) + getAssignmentNo().hashCode();
    hash = (37 * hash) + ASSIGNMENTDETAILS_FIELD_NUMBER;
    hash = (53 * hash) + getAssignmentDetails().hashCode();
    hash = (37 * hash) + DUEDATE_FIELD_NUMBER;
    hash = (53 * hash) + getDueDate().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smartclassroom.service2.DetailResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassroom.service2.DetailResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassroom.service2.DetailResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassroom.service2.DetailResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassroom.service2.DetailResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassroom.service2.DetailResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassroom.service2.DetailResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartclassroom.service2.DetailResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartclassroom.service2.DetailResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smartclassroom.service2.DetailResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartclassroom.service2.DetailResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartclassroom.service2.DetailResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smartclassroom.service2.DetailResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code DetailResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:DetailResponse)
      com.smartclassroom.service2.DetailResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartclassroom.service2.AssignmentService.internal_static_DetailResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartclassroom.service2.AssignmentService.internal_static_DetailResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartclassroom.service2.DetailResponse.class, com.smartclassroom.service2.DetailResponse.Builder.class);
    }

    // Construct using com.smartclassroom.service2.DetailResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      assignmentNo_ = "";

      assignmentDetails_ = "";

      dueDate_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smartclassroom.service2.AssignmentService.internal_static_DetailResponse_descriptor;
    }

    @java.lang.Override
    public com.smartclassroom.service2.DetailResponse getDefaultInstanceForType() {
      return com.smartclassroom.service2.DetailResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.smartclassroom.service2.DetailResponse build() {
      com.smartclassroom.service2.DetailResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smartclassroom.service2.DetailResponse buildPartial() {
      com.smartclassroom.service2.DetailResponse result = new com.smartclassroom.service2.DetailResponse(this);
      result.assignmentNo_ = assignmentNo_;
      result.assignmentDetails_ = assignmentDetails_;
      result.dueDate_ = dueDate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smartclassroom.service2.DetailResponse) {
        return mergeFrom((com.smartclassroom.service2.DetailResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smartclassroom.service2.DetailResponse other) {
      if (other == com.smartclassroom.service2.DetailResponse.getDefaultInstance()) return this;
      if (!other.getAssignmentNo().isEmpty()) {
        assignmentNo_ = other.assignmentNo_;
        onChanged();
      }
      if (!other.getAssignmentDetails().isEmpty()) {
        assignmentDetails_ = other.assignmentDetails_;
        onChanged();
      }
      if (!other.getDueDate().isEmpty()) {
        dueDate_ = other.dueDate_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smartclassroom.service2.DetailResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smartclassroom.service2.DetailResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object assignmentNo_ = "";
    /**
     * <code>string assignmentNo = 1;</code>
     */
    public java.lang.String getAssignmentNo() {
      java.lang.Object ref = assignmentNo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assignmentNo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string assignmentNo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAssignmentNoBytes() {
      java.lang.Object ref = assignmentNo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assignmentNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string assignmentNo = 1;</code>
     */
    public Builder setAssignmentNo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assignmentNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string assignmentNo = 1;</code>
     */
    public Builder clearAssignmentNo() {
      
      assignmentNo_ = getDefaultInstance().getAssignmentNo();
      onChanged();
      return this;
    }
    /**
     * <code>string assignmentNo = 1;</code>
     */
    public Builder setAssignmentNoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assignmentNo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object assignmentDetails_ = "";
    /**
     * <code>string assignmentDetails = 2;</code>
     */
    public java.lang.String getAssignmentDetails() {
      java.lang.Object ref = assignmentDetails_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assignmentDetails_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string assignmentDetails = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAssignmentDetailsBytes() {
      java.lang.Object ref = assignmentDetails_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assignmentDetails_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string assignmentDetails = 2;</code>
     */
    public Builder setAssignmentDetails(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assignmentDetails_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string assignmentDetails = 2;</code>
     */
    public Builder clearAssignmentDetails() {
      
      assignmentDetails_ = getDefaultInstance().getAssignmentDetails();
      onChanged();
      return this;
    }
    /**
     * <code>string assignmentDetails = 2;</code>
     */
    public Builder setAssignmentDetailsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assignmentDetails_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dueDate_ = "";
    /**
     * <code>string dueDate = 3;</code>
     */
    public java.lang.String getDueDate() {
      java.lang.Object ref = dueDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dueDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dueDate = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDueDateBytes() {
      java.lang.Object ref = dueDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dueDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dueDate = 3;</code>
     */
    public Builder setDueDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dueDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string dueDate = 3;</code>
     */
    public Builder clearDueDate() {
      
      dueDate_ = getDefaultInstance().getDueDate();
      onChanged();
      return this;
    }
    /**
     * <code>string dueDate = 3;</code>
     */
    public Builder setDueDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dueDate_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:DetailResponse)
  }

  // @@protoc_insertion_point(class_scope:DetailResponse)
  private static final com.smartclassroom.service2.DetailResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smartclassroom.service2.DetailResponse();
  }

  public static com.smartclassroom.service2.DetailResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DetailResponse>
      PARSER = new com.google.protobuf.AbstractParser<DetailResponse>() {
    @java.lang.Override
    public DetailResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DetailResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DetailResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DetailResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smartclassroom.service2.DetailResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

