// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AssignmentService.proto

package com.smartclassroom.service2;

public interface ReminderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReminderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reminder = 1;</code>
   */
  java.lang.String getReminder();
  /**
   * <code>string reminder = 1;</code>
   */
  com.google.protobuf.ByteString
      getReminderBytes();
}
