// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AssignmentService.proto

package com.smartclassroom.service2;

public interface ReminderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReminderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string subject = 1;</code>
   */
  java.lang.String getSubject();
  /**
   * <code>string subject = 1;</code>
   */
  com.google.protobuf.ByteString
      getSubjectBytes();
}
