// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AssignmentService.proto

package com.smartclassroom.service2;

public interface SubmitRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubmitRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string subjectName = 1;</code>
   */
  java.lang.String getSubjectName();
  /**
   * <code>string subjectName = 1;</code>
   */
  com.google.protobuf.ByteString
      getSubjectNameBytes();

  /**
   * <code>string assignment = 2;</code>
   */
  java.lang.String getAssignment();
  /**
   * <code>string assignment = 2;</code>
   */
  com.google.protobuf.ByteString
      getAssignmentBytes();

  /**
   * <code>string attachment = 3;</code>
   */
  java.lang.String getAttachment();
  /**
   * <code>string attachment = 3;</code>
   */
  com.google.protobuf.ByteString
      getAttachmentBytes();

  /**
   * <code>string currentDate = 4;</code>
   */
  java.lang.String getCurrentDate();
  /**
   * <code>string currentDate = 4;</code>
   */
  com.google.protobuf.ByteString
      getCurrentDateBytes();
}
