// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AssignmentService.proto

package com.smartclassroom.service2;

/**
 * Protobuf type {@code SubmitRequest}
 */
public  final class SubmitRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SubmitRequest)
    SubmitRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SubmitRequest.newBuilder() to construct.
  private SubmitRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SubmitRequest() {
    subjectName_ = "";
    assignment_ = "";
    attachment_ = "";
    currentDate_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private SubmitRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            subjectName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            assignment_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            attachment_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            currentDate_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smartclassroom.service2.AssignmentService.internal_static_SubmitRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smartclassroom.service2.AssignmentService.internal_static_SubmitRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smartclassroom.service2.SubmitRequest.class, com.smartclassroom.service2.SubmitRequest.Builder.class);
  }

  public static final int SUBJECTNAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object subjectName_;
  /**
   * <code>string subjectName = 1;</code>
   */
  public java.lang.String getSubjectName() {
    java.lang.Object ref = subjectName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      subjectName_ = s;
      return s;
    }
  }
  /**
   * <code>string subjectName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSubjectNameBytes() {
    java.lang.Object ref = subjectName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      subjectName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ASSIGNMENT_FIELD_NUMBER = 2;
  private volatile java.lang.Object assignment_;
  /**
   * <code>string assignment = 2;</code>
   */
  public java.lang.String getAssignment() {
    java.lang.Object ref = assignment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      assignment_ = s;
      return s;
    }
  }
  /**
   * <code>string assignment = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAssignmentBytes() {
    java.lang.Object ref = assignment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      assignment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTACHMENT_FIELD_NUMBER = 3;
  private volatile java.lang.Object attachment_;
  /**
   * <code>string attachment = 3;</code>
   */
  public java.lang.String getAttachment() {
    java.lang.Object ref = attachment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      attachment_ = s;
      return s;
    }
  }
  /**
   * <code>string attachment = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAttachmentBytes() {
    java.lang.Object ref = attachment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      attachment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENTDATE_FIELD_NUMBER = 4;
  private volatile java.lang.Object currentDate_;
  /**
   * <code>string currentDate = 4;</code>
   */
  public java.lang.String getCurrentDate() {
    java.lang.Object ref = currentDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      currentDate_ = s;
      return s;
    }
  }
  /**
   * <code>string currentDate = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCurrentDateBytes() {
    java.lang.Object ref = currentDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      currentDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSubjectNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, subjectName_);
    }
    if (!getAssignmentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, assignment_);
    }
    if (!getAttachmentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, attachment_);
    }
    if (!getCurrentDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, currentDate_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSubjectNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, subjectName_);
    }
    if (!getAssignmentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, assignment_);
    }
    if (!getAttachmentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, attachment_);
    }
    if (!getCurrentDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, currentDate_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smartclassroom.service2.SubmitRequest)) {
      return super.equals(obj);
    }
    com.smartclassroom.service2.SubmitRequest other = (com.smartclassroom.service2.SubmitRequest) obj;

    boolean result = true;
    result = result && getSubjectName()
        .equals(other.getSubjectName());
    result = result && getAssignment()
        .equals(other.getAssignment());
    result = result && getAttachment()
        .equals(other.getAttachment());
    result = result && getCurrentDate()
        .equals(other.getCurrentDate());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SUBJECTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getSubjectName().hashCode();
    hash = (37 * hash) + ASSIGNMENT_FIELD_NUMBER;
    hash = (53 * hash) + getAssignment().hashCode();
    hash = (37 * hash) + ATTACHMENT_FIELD_NUMBER;
    hash = (53 * hash) + getAttachment().hashCode();
    hash = (37 * hash) + CURRENTDATE_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentDate().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smartclassroom.service2.SubmitRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassroom.service2.SubmitRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassroom.service2.SubmitRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassroom.service2.SubmitRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassroom.service2.SubmitRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassroom.service2.SubmitRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassroom.service2.SubmitRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartclassroom.service2.SubmitRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartclassroom.service2.SubmitRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smartclassroom.service2.SubmitRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartclassroom.service2.SubmitRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartclassroom.service2.SubmitRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smartclassroom.service2.SubmitRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SubmitRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SubmitRequest)
      com.smartclassroom.service2.SubmitRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartclassroom.service2.AssignmentService.internal_static_SubmitRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartclassroom.service2.AssignmentService.internal_static_SubmitRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartclassroom.service2.SubmitRequest.class, com.smartclassroom.service2.SubmitRequest.Builder.class);
    }

    // Construct using com.smartclassroom.service2.SubmitRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      subjectName_ = "";

      assignment_ = "";

      attachment_ = "";

      currentDate_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smartclassroom.service2.AssignmentService.internal_static_SubmitRequest_descriptor;
    }

    @java.lang.Override
    public com.smartclassroom.service2.SubmitRequest getDefaultInstanceForType() {
      return com.smartclassroom.service2.SubmitRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.smartclassroom.service2.SubmitRequest build() {
      com.smartclassroom.service2.SubmitRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smartclassroom.service2.SubmitRequest buildPartial() {
      com.smartclassroom.service2.SubmitRequest result = new com.smartclassroom.service2.SubmitRequest(this);
      result.subjectName_ = subjectName_;
      result.assignment_ = assignment_;
      result.attachment_ = attachment_;
      result.currentDate_ = currentDate_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smartclassroom.service2.SubmitRequest) {
        return mergeFrom((com.smartclassroom.service2.SubmitRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smartclassroom.service2.SubmitRequest other) {
      if (other == com.smartclassroom.service2.SubmitRequest.getDefaultInstance()) return this;
      if (!other.getSubjectName().isEmpty()) {
        subjectName_ = other.subjectName_;
        onChanged();
      }
      if (!other.getAssignment().isEmpty()) {
        assignment_ = other.assignment_;
        onChanged();
      }
      if (!other.getAttachment().isEmpty()) {
        attachment_ = other.attachment_;
        onChanged();
      }
      if (!other.getCurrentDate().isEmpty()) {
        currentDate_ = other.currentDate_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smartclassroom.service2.SubmitRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smartclassroom.service2.SubmitRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object subjectName_ = "";
    /**
     * <code>string subjectName = 1;</code>
     */
    public java.lang.String getSubjectName() {
      java.lang.Object ref = subjectName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        subjectName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string subjectName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSubjectNameBytes() {
      java.lang.Object ref = subjectName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subjectName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string subjectName = 1;</code>
     */
    public Builder setSubjectName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      subjectName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string subjectName = 1;</code>
     */
    public Builder clearSubjectName() {
      
      subjectName_ = getDefaultInstance().getSubjectName();
      onChanged();
      return this;
    }
    /**
     * <code>string subjectName = 1;</code>
     */
    public Builder setSubjectNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      subjectName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object assignment_ = "";
    /**
     * <code>string assignment = 2;</code>
     */
    public java.lang.String getAssignment() {
      java.lang.Object ref = assignment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        assignment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string assignment = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAssignmentBytes() {
      java.lang.Object ref = assignment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        assignment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string assignment = 2;</code>
     */
    public Builder setAssignment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      assignment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string assignment = 2;</code>
     */
    public Builder clearAssignment() {
      
      assignment_ = getDefaultInstance().getAssignment();
      onChanged();
      return this;
    }
    /**
     * <code>string assignment = 2;</code>
     */
    public Builder setAssignmentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      assignment_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object attachment_ = "";
    /**
     * <code>string attachment = 3;</code>
     */
    public java.lang.String getAttachment() {
      java.lang.Object ref = attachment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        attachment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string attachment = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAttachmentBytes() {
      java.lang.Object ref = attachment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        attachment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string attachment = 3;</code>
     */
    public Builder setAttachment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      attachment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string attachment = 3;</code>
     */
    public Builder clearAttachment() {
      
      attachment_ = getDefaultInstance().getAttachment();
      onChanged();
      return this;
    }
    /**
     * <code>string attachment = 3;</code>
     */
    public Builder setAttachmentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      attachment_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object currentDate_ = "";
    /**
     * <code>string currentDate = 4;</code>
     */
    public java.lang.String getCurrentDate() {
      java.lang.Object ref = currentDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string currentDate = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCurrentDateBytes() {
      java.lang.Object ref = currentDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string currentDate = 4;</code>
     */
    public Builder setCurrentDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      currentDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string currentDate = 4;</code>
     */
    public Builder clearCurrentDate() {
      
      currentDate_ = getDefaultInstance().getCurrentDate();
      onChanged();
      return this;
    }
    /**
     * <code>string currentDate = 4;</code>
     */
    public Builder setCurrentDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      currentDate_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SubmitRequest)
  }

  // @@protoc_insertion_point(class_scope:SubmitRequest)
  private static final com.smartclassroom.service2.SubmitRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smartclassroom.service2.SubmitRequest();
  }

  public static com.smartclassroom.service2.SubmitRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubmitRequest>
      PARSER = new com.google.protobuf.AbstractParser<SubmitRequest>() {
    @java.lang.Override
    public SubmitRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new SubmitRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SubmitRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubmitRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smartclassroom.service2.SubmitRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

