// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AssignmentService.proto

package com.smartclassroom.service2;

public interface SubmitResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SubmitResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string status = 1;</code>
   */
  java.util.List<java.lang.String>
      getStatusList();
  /**
   * <code>repeated string status = 1;</code>
   */
  int getStatusCount();
  /**
   * <code>repeated string status = 1;</code>
   */
  java.lang.String getStatus(int index);
  /**
   * <code>repeated string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes(int index);
}
