// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartclassrooms.proto

package com.smartclassrooms;

public interface NotificationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NotificationRequest)
    com.google.protobuf.MessageOrBuilder {
}
