// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartclassrooms.proto

package com.smartclassrooms;

/**
 * Protobuf type {@code ReportResponse}
 */
public  final class ReportResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ReportResponse)
    ReportResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReportResponse.newBuilder() to construct.
  private ReportResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReportResponse() {
    studentAttendances_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReportResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              studentAttendances_ = new java.util.ArrayList<com.smartclassrooms.StudentAttendance>();
              mutable_bitField0_ |= 0x00000001;
            }
            studentAttendances_.add(
                input.readMessage(com.smartclassrooms.StudentAttendance.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        studentAttendances_ = java.util.Collections.unmodifiableList(studentAttendances_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smartclassrooms.Smartclassrooms.internal_static_ReportResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smartclassrooms.Smartclassrooms.internal_static_ReportResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smartclassrooms.ReportResponse.class, com.smartclassrooms.ReportResponse.Builder.class);
  }

  public static final int STUDENTATTENDANCES_FIELD_NUMBER = 1;
  private java.util.List<com.smartclassrooms.StudentAttendance> studentAttendances_;
  /**
   * <code>repeated .StudentAttendance studentAttendances = 1;</code>
   */
  public java.util.List<com.smartclassrooms.StudentAttendance> getStudentAttendancesList() {
    return studentAttendances_;
  }
  /**
   * <code>repeated .StudentAttendance studentAttendances = 1;</code>
   */
  public java.util.List<? extends com.smartclassrooms.StudentAttendanceOrBuilder> 
      getStudentAttendancesOrBuilderList() {
    return studentAttendances_;
  }
  /**
   * <code>repeated .StudentAttendance studentAttendances = 1;</code>
   */
  public int getStudentAttendancesCount() {
    return studentAttendances_.size();
  }
  /**
   * <code>repeated .StudentAttendance studentAttendances = 1;</code>
   */
  public com.smartclassrooms.StudentAttendance getStudentAttendances(int index) {
    return studentAttendances_.get(index);
  }
  /**
   * <code>repeated .StudentAttendance studentAttendances = 1;</code>
   */
  public com.smartclassrooms.StudentAttendanceOrBuilder getStudentAttendancesOrBuilder(
      int index) {
    return studentAttendances_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < studentAttendances_.size(); i++) {
      output.writeMessage(1, studentAttendances_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < studentAttendances_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, studentAttendances_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smartclassrooms.ReportResponse)) {
      return super.equals(obj);
    }
    com.smartclassrooms.ReportResponse other = (com.smartclassrooms.ReportResponse) obj;

    boolean result = true;
    result = result && getStudentAttendancesList()
        .equals(other.getStudentAttendancesList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getStudentAttendancesCount() > 0) {
      hash = (37 * hash) + STUDENTATTENDANCES_FIELD_NUMBER;
      hash = (53 * hash) + getStudentAttendancesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smartclassrooms.ReportResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassrooms.ReportResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassrooms.ReportResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassrooms.ReportResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassrooms.ReportResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassrooms.ReportResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassrooms.ReportResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartclassrooms.ReportResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartclassrooms.ReportResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smartclassrooms.ReportResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartclassrooms.ReportResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartclassrooms.ReportResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smartclassrooms.ReportResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ReportResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ReportResponse)
      com.smartclassrooms.ReportResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartclassrooms.Smartclassrooms.internal_static_ReportResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartclassrooms.Smartclassrooms.internal_static_ReportResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartclassrooms.ReportResponse.class, com.smartclassrooms.ReportResponse.Builder.class);
    }

    // Construct using com.smartclassrooms.ReportResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getStudentAttendancesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (studentAttendancesBuilder_ == null) {
        studentAttendances_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        studentAttendancesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smartclassrooms.Smartclassrooms.internal_static_ReportResponse_descriptor;
    }

    @java.lang.Override
    public com.smartclassrooms.ReportResponse getDefaultInstanceForType() {
      return com.smartclassrooms.ReportResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.smartclassrooms.ReportResponse build() {
      com.smartclassrooms.ReportResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smartclassrooms.ReportResponse buildPartial() {
      com.smartclassrooms.ReportResponse result = new com.smartclassrooms.ReportResponse(this);
      int from_bitField0_ = bitField0_;
      if (studentAttendancesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          studentAttendances_ = java.util.Collections.unmodifiableList(studentAttendances_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.studentAttendances_ = studentAttendances_;
      } else {
        result.studentAttendances_ = studentAttendancesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smartclassrooms.ReportResponse) {
        return mergeFrom((com.smartclassrooms.ReportResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smartclassrooms.ReportResponse other) {
      if (other == com.smartclassrooms.ReportResponse.getDefaultInstance()) return this;
      if (studentAttendancesBuilder_ == null) {
        if (!other.studentAttendances_.isEmpty()) {
          if (studentAttendances_.isEmpty()) {
            studentAttendances_ = other.studentAttendances_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStudentAttendancesIsMutable();
            studentAttendances_.addAll(other.studentAttendances_);
          }
          onChanged();
        }
      } else {
        if (!other.studentAttendances_.isEmpty()) {
          if (studentAttendancesBuilder_.isEmpty()) {
            studentAttendancesBuilder_.dispose();
            studentAttendancesBuilder_ = null;
            studentAttendances_ = other.studentAttendances_;
            bitField0_ = (bitField0_ & ~0x00000001);
            studentAttendancesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getStudentAttendancesFieldBuilder() : null;
          } else {
            studentAttendancesBuilder_.addAllMessages(other.studentAttendances_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smartclassrooms.ReportResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smartclassrooms.ReportResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.smartclassrooms.StudentAttendance> studentAttendances_ =
      java.util.Collections.emptyList();
    private void ensureStudentAttendancesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        studentAttendances_ = new java.util.ArrayList<com.smartclassrooms.StudentAttendance>(studentAttendances_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.smartclassrooms.StudentAttendance, com.smartclassrooms.StudentAttendance.Builder, com.smartclassrooms.StudentAttendanceOrBuilder> studentAttendancesBuilder_;

    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public java.util.List<com.smartclassrooms.StudentAttendance> getStudentAttendancesList() {
      if (studentAttendancesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(studentAttendances_);
      } else {
        return studentAttendancesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public int getStudentAttendancesCount() {
      if (studentAttendancesBuilder_ == null) {
        return studentAttendances_.size();
      } else {
        return studentAttendancesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public com.smartclassrooms.StudentAttendance getStudentAttendances(int index) {
      if (studentAttendancesBuilder_ == null) {
        return studentAttendances_.get(index);
      } else {
        return studentAttendancesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public Builder setStudentAttendances(
        int index, com.smartclassrooms.StudentAttendance value) {
      if (studentAttendancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentAttendancesIsMutable();
        studentAttendances_.set(index, value);
        onChanged();
      } else {
        studentAttendancesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public Builder setStudentAttendances(
        int index, com.smartclassrooms.StudentAttendance.Builder builderForValue) {
      if (studentAttendancesBuilder_ == null) {
        ensureStudentAttendancesIsMutable();
        studentAttendances_.set(index, builderForValue.build());
        onChanged();
      } else {
        studentAttendancesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public Builder addStudentAttendances(com.smartclassrooms.StudentAttendance value) {
      if (studentAttendancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentAttendancesIsMutable();
        studentAttendances_.add(value);
        onChanged();
      } else {
        studentAttendancesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public Builder addStudentAttendances(
        int index, com.smartclassrooms.StudentAttendance value) {
      if (studentAttendancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStudentAttendancesIsMutable();
        studentAttendances_.add(index, value);
        onChanged();
      } else {
        studentAttendancesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public Builder addStudentAttendances(
        com.smartclassrooms.StudentAttendance.Builder builderForValue) {
      if (studentAttendancesBuilder_ == null) {
        ensureStudentAttendancesIsMutable();
        studentAttendances_.add(builderForValue.build());
        onChanged();
      } else {
        studentAttendancesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public Builder addStudentAttendances(
        int index, com.smartclassrooms.StudentAttendance.Builder builderForValue) {
      if (studentAttendancesBuilder_ == null) {
        ensureStudentAttendancesIsMutable();
        studentAttendances_.add(index, builderForValue.build());
        onChanged();
      } else {
        studentAttendancesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public Builder addAllStudentAttendances(
        java.lang.Iterable<? extends com.smartclassrooms.StudentAttendance> values) {
      if (studentAttendancesBuilder_ == null) {
        ensureStudentAttendancesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, studentAttendances_);
        onChanged();
      } else {
        studentAttendancesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public Builder clearStudentAttendances() {
      if (studentAttendancesBuilder_ == null) {
        studentAttendances_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        studentAttendancesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public Builder removeStudentAttendances(int index) {
      if (studentAttendancesBuilder_ == null) {
        ensureStudentAttendancesIsMutable();
        studentAttendances_.remove(index);
        onChanged();
      } else {
        studentAttendancesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public com.smartclassrooms.StudentAttendance.Builder getStudentAttendancesBuilder(
        int index) {
      return getStudentAttendancesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public com.smartclassrooms.StudentAttendanceOrBuilder getStudentAttendancesOrBuilder(
        int index) {
      if (studentAttendancesBuilder_ == null) {
        return studentAttendances_.get(index);  } else {
        return studentAttendancesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public java.util.List<? extends com.smartclassrooms.StudentAttendanceOrBuilder> 
         getStudentAttendancesOrBuilderList() {
      if (studentAttendancesBuilder_ != null) {
        return studentAttendancesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(studentAttendances_);
      }
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public com.smartclassrooms.StudentAttendance.Builder addStudentAttendancesBuilder() {
      return getStudentAttendancesFieldBuilder().addBuilder(
          com.smartclassrooms.StudentAttendance.getDefaultInstance());
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public com.smartclassrooms.StudentAttendance.Builder addStudentAttendancesBuilder(
        int index) {
      return getStudentAttendancesFieldBuilder().addBuilder(
          index, com.smartclassrooms.StudentAttendance.getDefaultInstance());
    }
    /**
     * <code>repeated .StudentAttendance studentAttendances = 1;</code>
     */
    public java.util.List<com.smartclassrooms.StudentAttendance.Builder> 
         getStudentAttendancesBuilderList() {
      return getStudentAttendancesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.smartclassrooms.StudentAttendance, com.smartclassrooms.StudentAttendance.Builder, com.smartclassrooms.StudentAttendanceOrBuilder> 
        getStudentAttendancesFieldBuilder() {
      if (studentAttendancesBuilder_ == null) {
        studentAttendancesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.smartclassrooms.StudentAttendance, com.smartclassrooms.StudentAttendance.Builder, com.smartclassrooms.StudentAttendanceOrBuilder>(
                studentAttendances_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        studentAttendances_ = null;
      }
      return studentAttendancesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ReportResponse)
  }

  // @@protoc_insertion_point(class_scope:ReportResponse)
  private static final com.smartclassrooms.ReportResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smartclassrooms.ReportResponse();
  }

  public static com.smartclassrooms.ReportResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReportResponse>
      PARSER = new com.google.protobuf.AbstractParser<ReportResponse>() {
    @java.lang.Override
    public ReportResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReportResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReportResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReportResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smartclassrooms.ReportResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

