// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartclassrooms.proto

package com.smartclassrooms;

public interface ReportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReportRequest)
    com.google.protobuf.MessageOrBuilder {
}
