// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartclassrooms.proto

package com.smartclassrooms;

public final class Smartclassrooms {
  private Smartclassrooms() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TrackRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TrackRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TrackResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TrackResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReportRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReportRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReportResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReportResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_StudentAttendance_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_StudentAttendance_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NotificationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NotificationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NotificationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_NotificationResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025smartclassrooms.proto\"/\n\014TrackRequest\022" +
      "\021\n\tstudentID\030\001 \001(\t\022\014\n\004RFID\030\002 \001(\t\"1\n\rTrac" +
      "kResponse\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 " +
      "\001(\t\"\017\n\rReportRequest\"@\n\016ReportResponse\022." +
      "\n\022studentAttendances\030\001 \003(\0132\022.StudentAtte" +
      "ndance\"L\n\021StudentAttendance\022\021\n\tstudentID" +
      "\030\001 \001(\t\022\023\n\013studentName\030\002 \001(\t\022\017\n\007present\030\003" +
      " \001(\010\"\025\n\023NotificationRequest\"(\n\024Notificat" +
      "ionResponse\022\020\n\010messages\030\001 \003(\t2\307\001\n\nAttend" +
      "ance\0225\n\022AttendanceTracking\022\r.TrackReques" +
      "t\032\016.TrackResponse\"\000\0227\n\020AttendanceReport\022" +
      "\016.ReportRequest\032\017.ReportResponse\"\0000\001\022I\n\026" +
      "AttendanceNotification\022\024.NotificationReq" +
      "uest\032\025.NotificationResponse\"\0000\001B\027\n\023com.s" +
      "martclassroomsP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TrackRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TrackRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TrackRequest_descriptor,
        new java.lang.String[] { "StudentID", "RFID", });
    internal_static_TrackResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TrackResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TrackResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_ReportRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ReportRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReportRequest_descriptor,
        new java.lang.String[] { });
    internal_static_ReportResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ReportResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReportResponse_descriptor,
        new java.lang.String[] { "StudentAttendances", });
    internal_static_StudentAttendance_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_StudentAttendance_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_StudentAttendance_descriptor,
        new java.lang.String[] { "StudentID", "StudentName", "Present", });
    internal_static_NotificationRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_NotificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NotificationRequest_descriptor,
        new java.lang.String[] { });
    internal_static_NotificationResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_NotificationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_NotificationResponse_descriptor,
        new java.lang.String[] { "Messages", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
