// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartclassrooms.proto

package com.smartclassrooms;

public interface StudentAttendanceOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StudentAttendance)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string studentID = 1;</code>
   */
  java.lang.String getStudentID();
  /**
   * <code>string studentID = 1;</code>
   */
  com.google.protobuf.ByteString
      getStudentIDBytes();

  /**
   * <code>string studentName = 2;</code>
   */
  java.lang.String getStudentName();
  /**
   * <code>string studentName = 2;</code>
   */
  com.google.protobuf.ByteString
      getStudentNameBytes();

  /**
   * <code>bool present = 3;</code>
   */
  boolean getPresent();
}
