// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartclassrooms.proto

package com.smartclassrooms;

public interface TrackResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrackResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
