// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AttendanceService.proto

package com.smartclassroom.service1;

public interface NotificationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NotificationRequest)
    com.google.protobuf.MessageOrBuilder {
}
