// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AttendanceService.proto

package com.smartclassroom.service1;

public interface ReportResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReportResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .StudentAttendance studentAttendances = 1;</code>
   */
  java.util.List<com.smartclassroom.service1.StudentAttendance> 
      getStudentAttendancesList();
  /**
   * <code>repeated .StudentAttendance studentAttendances = 1;</code>
   */
  com.smartclassroom.service1.StudentAttendance getStudentAttendances(int index);
  /**
   * <code>repeated .StudentAttendance studentAttendances = 1;</code>
   */
  int getStudentAttendancesCount();
  /**
   * <code>repeated .StudentAttendance studentAttendances = 1;</code>
   */
  java.util.List<? extends com.smartclassroom.service1.StudentAttendanceOrBuilder> 
      getStudentAttendancesOrBuilderList();
  /**
   * <code>repeated .StudentAttendance studentAttendances = 1;</code>
   */
  com.smartclassroom.service1.StudentAttendanceOrBuilder getStudentAttendancesOrBuilder(
      int index);
}
