// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AttendanceService.proto

package com.smartclassroom.service1;

public interface ReportRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ReportRequest)
    com.google.protobuf.MessageOrBuilder {
}
