// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AttendanceService.proto

package com.smartclassroom.service1;

/**
 * Protobuf type {@code StudentAttendance}
 */
public  final class StudentAttendance extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:StudentAttendance)
    StudentAttendanceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use StudentAttendance.newBuilder() to construct.
  private StudentAttendance(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private StudentAttendance() {
    studentID_ = "";
    studentName_ = "";
    present_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private StudentAttendance(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            studentID_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            studentName_ = s;
            break;
          }
          case 24: {

            present_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smartclassroom.service1.AttendanceService.internal_static_StudentAttendance_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smartclassroom.service1.AttendanceService.internal_static_StudentAttendance_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smartclassroom.service1.StudentAttendance.class, com.smartclassroom.service1.StudentAttendance.Builder.class);
  }

  public static final int STUDENTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object studentID_;
  /**
   * <code>string studentID = 1;</code>
   */
  public java.lang.String getStudentID() {
    java.lang.Object ref = studentID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      studentID_ = s;
      return s;
    }
  }
  /**
   * <code>string studentID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStudentIDBytes() {
    java.lang.Object ref = studentID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      studentID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STUDENTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object studentName_;
  /**
   * <code>string studentName = 2;</code>
   */
  public java.lang.String getStudentName() {
    java.lang.Object ref = studentName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      studentName_ = s;
      return s;
    }
  }
  /**
   * <code>string studentName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getStudentNameBytes() {
    java.lang.Object ref = studentName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      studentName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRESENT_FIELD_NUMBER = 3;
  private boolean present_;
  /**
   * <code>bool present = 3;</code>
   */
  public boolean getPresent() {
    return present_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStudentIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, studentID_);
    }
    if (!getStudentNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, studentName_);
    }
    if (present_ != false) {
      output.writeBool(3, present_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStudentIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, studentID_);
    }
    if (!getStudentNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, studentName_);
    }
    if (present_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, present_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smartclassroom.service1.StudentAttendance)) {
      return super.equals(obj);
    }
    com.smartclassroom.service1.StudentAttendance other = (com.smartclassroom.service1.StudentAttendance) obj;

    boolean result = true;
    result = result && getStudentID()
        .equals(other.getStudentID());
    result = result && getStudentName()
        .equals(other.getStudentName());
    result = result && (getPresent()
        == other.getPresent());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STUDENTID_FIELD_NUMBER;
    hash = (53 * hash) + getStudentID().hashCode();
    hash = (37 * hash) + STUDENTNAME_FIELD_NUMBER;
    hash = (53 * hash) + getStudentName().hashCode();
    hash = (37 * hash) + PRESENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getPresent());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smartclassroom.service1.StudentAttendance parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassroom.service1.StudentAttendance parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassroom.service1.StudentAttendance parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassroom.service1.StudentAttendance parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassroom.service1.StudentAttendance parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartclassroom.service1.StudentAttendance parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartclassroom.service1.StudentAttendance parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartclassroom.service1.StudentAttendance parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartclassroom.service1.StudentAttendance parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smartclassroom.service1.StudentAttendance parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartclassroom.service1.StudentAttendance parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartclassroom.service1.StudentAttendance parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smartclassroom.service1.StudentAttendance prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code StudentAttendance}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:StudentAttendance)
      com.smartclassroom.service1.StudentAttendanceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartclassroom.service1.AttendanceService.internal_static_StudentAttendance_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartclassroom.service1.AttendanceService.internal_static_StudentAttendance_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartclassroom.service1.StudentAttendance.class, com.smartclassroom.service1.StudentAttendance.Builder.class);
    }

    // Construct using com.smartclassroom.service1.StudentAttendance.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      studentID_ = "";

      studentName_ = "";

      present_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smartclassroom.service1.AttendanceService.internal_static_StudentAttendance_descriptor;
    }

    @java.lang.Override
    public com.smartclassroom.service1.StudentAttendance getDefaultInstanceForType() {
      return com.smartclassroom.service1.StudentAttendance.getDefaultInstance();
    }

    @java.lang.Override
    public com.smartclassroom.service1.StudentAttendance build() {
      com.smartclassroom.service1.StudentAttendance result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smartclassroom.service1.StudentAttendance buildPartial() {
      com.smartclassroom.service1.StudentAttendance result = new com.smartclassroom.service1.StudentAttendance(this);
      result.studentID_ = studentID_;
      result.studentName_ = studentName_;
      result.present_ = present_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smartclassroom.service1.StudentAttendance) {
        return mergeFrom((com.smartclassroom.service1.StudentAttendance)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smartclassroom.service1.StudentAttendance other) {
      if (other == com.smartclassroom.service1.StudentAttendance.getDefaultInstance()) return this;
      if (!other.getStudentID().isEmpty()) {
        studentID_ = other.studentID_;
        onChanged();
      }
      if (!other.getStudentName().isEmpty()) {
        studentName_ = other.studentName_;
        onChanged();
      }
      if (other.getPresent() != false) {
        setPresent(other.getPresent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smartclassroom.service1.StudentAttendance parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smartclassroom.service1.StudentAttendance) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object studentID_ = "";
    /**
     * <code>string studentID = 1;</code>
     */
    public java.lang.String getStudentID() {
      java.lang.Object ref = studentID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studentID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string studentID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStudentIDBytes() {
      java.lang.Object ref = studentID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studentID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string studentID = 1;</code>
     */
    public Builder setStudentID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      studentID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string studentID = 1;</code>
     */
    public Builder clearStudentID() {
      
      studentID_ = getDefaultInstance().getStudentID();
      onChanged();
      return this;
    }
    /**
     * <code>string studentID = 1;</code>
     */
    public Builder setStudentIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      studentID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object studentName_ = "";
    /**
     * <code>string studentName = 2;</code>
     */
    public java.lang.String getStudentName() {
      java.lang.Object ref = studentName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studentName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string studentName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStudentNameBytes() {
      java.lang.Object ref = studentName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studentName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string studentName = 2;</code>
     */
    public Builder setStudentName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      studentName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string studentName = 2;</code>
     */
    public Builder clearStudentName() {
      
      studentName_ = getDefaultInstance().getStudentName();
      onChanged();
      return this;
    }
    /**
     * <code>string studentName = 2;</code>
     */
    public Builder setStudentNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      studentName_ = value;
      onChanged();
      return this;
    }

    private boolean present_ ;
    /**
     * <code>bool present = 3;</code>
     */
    public boolean getPresent() {
      return present_;
    }
    /**
     * <code>bool present = 3;</code>
     */
    public Builder setPresent(boolean value) {
      
      present_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool present = 3;</code>
     */
    public Builder clearPresent() {
      
      present_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:StudentAttendance)
  }

  // @@protoc_insertion_point(class_scope:StudentAttendance)
  private static final com.smartclassroom.service1.StudentAttendance DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smartclassroom.service1.StudentAttendance();
  }

  public static com.smartclassroom.service1.StudentAttendance getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StudentAttendance>
      PARSER = new com.google.protobuf.AbstractParser<StudentAttendance>() {
    @java.lang.Override
    public StudentAttendance parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new StudentAttendance(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<StudentAttendance> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StudentAttendance> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smartclassroom.service1.StudentAttendance getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

