// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AttendanceService.proto

package com.smartclassroom.service1;

public interface TrackRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TrackRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string studentID = 1;</code>
   */
  java.lang.String getStudentID();
  /**
   * <code>string studentID = 1;</code>
   */
  com.google.protobuf.ByteString
      getStudentIDBytes();

  /**
   * <code>string RFID = 2;</code>
   */
  java.lang.String getRFID();
  /**
   * <code>string RFID = 2;</code>
   */
  com.google.protobuf.ByteString
      getRFIDBytes();
}
