// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SCService1.proto

package com.smartClass.SCService1;

public interface getStudentAttendanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:getStudentAttendanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tStudentID = 1;</code>
   */
  java.lang.String getTStudentID();
  /**
   * <code>string tStudentID = 1;</code>
   */
  com.google.protobuf.ByteString
      getTStudentIDBytes();
}
