// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SCService1.proto

package com.smartClass.SCService1;

/**
 * Protobuf type {@code getStudentAttendanceRequest}
 */
public  final class getStudentAttendanceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:getStudentAttendanceRequest)
    getStudentAttendanceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use getStudentAttendanceRequest.newBuilder() to construct.
  private getStudentAttendanceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private getStudentAttendanceRequest() {
    tStudentID_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private getStudentAttendanceRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            tStudentID_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smartClass.SCService1.SCService1Impl.internal_static_getStudentAttendanceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smartClass.SCService1.SCService1Impl.internal_static_getStudentAttendanceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smartClass.SCService1.getStudentAttendanceRequest.class, com.smartClass.SCService1.getStudentAttendanceRequest.Builder.class);
  }

  public static final int TSTUDENTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object tStudentID_;
  /**
   * <code>string tStudentID = 1;</code>
   */
  public java.lang.String getTStudentID() {
    java.lang.Object ref = tStudentID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tStudentID_ = s;
      return s;
    }
  }
  /**
   * <code>string tStudentID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTStudentIDBytes() {
    java.lang.Object ref = tStudentID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tStudentID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTStudentIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tStudentID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTStudentIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tStudentID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smartClass.SCService1.getStudentAttendanceRequest)) {
      return super.equals(obj);
    }
    com.smartClass.SCService1.getStudentAttendanceRequest other = (com.smartClass.SCService1.getStudentAttendanceRequest) obj;

    boolean result = true;
    result = result && getTStudentID()
        .equals(other.getTStudentID());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TSTUDENTID_FIELD_NUMBER;
    hash = (53 * hash) + getTStudentID().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smartClass.SCService1.getStudentAttendanceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartClass.SCService1.getStudentAttendanceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartClass.SCService1.getStudentAttendanceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartClass.SCService1.getStudentAttendanceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartClass.SCService1.getStudentAttendanceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartClass.SCService1.getStudentAttendanceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartClass.SCService1.getStudentAttendanceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartClass.SCService1.getStudentAttendanceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartClass.SCService1.getStudentAttendanceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smartClass.SCService1.getStudentAttendanceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartClass.SCService1.getStudentAttendanceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartClass.SCService1.getStudentAttendanceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smartClass.SCService1.getStudentAttendanceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code getStudentAttendanceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:getStudentAttendanceRequest)
      com.smartClass.SCService1.getStudentAttendanceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartClass.SCService1.SCService1Impl.internal_static_getStudentAttendanceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartClass.SCService1.SCService1Impl.internal_static_getStudentAttendanceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartClass.SCService1.getStudentAttendanceRequest.class, com.smartClass.SCService1.getStudentAttendanceRequest.Builder.class);
    }

    // Construct using com.smartClass.SCService1.getStudentAttendanceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      tStudentID_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smartClass.SCService1.SCService1Impl.internal_static_getStudentAttendanceRequest_descriptor;
    }

    @java.lang.Override
    public com.smartClass.SCService1.getStudentAttendanceRequest getDefaultInstanceForType() {
      return com.smartClass.SCService1.getStudentAttendanceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.smartClass.SCService1.getStudentAttendanceRequest build() {
      com.smartClass.SCService1.getStudentAttendanceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smartClass.SCService1.getStudentAttendanceRequest buildPartial() {
      com.smartClass.SCService1.getStudentAttendanceRequest result = new com.smartClass.SCService1.getStudentAttendanceRequest(this);
      result.tStudentID_ = tStudentID_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smartClass.SCService1.getStudentAttendanceRequest) {
        return mergeFrom((com.smartClass.SCService1.getStudentAttendanceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smartClass.SCService1.getStudentAttendanceRequest other) {
      if (other == com.smartClass.SCService1.getStudentAttendanceRequest.getDefaultInstance()) return this;
      if (!other.getTStudentID().isEmpty()) {
        tStudentID_ = other.tStudentID_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smartClass.SCService1.getStudentAttendanceRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smartClass.SCService1.getStudentAttendanceRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object tStudentID_ = "";
    /**
     * <code>string tStudentID = 1;</code>
     */
    public java.lang.String getTStudentID() {
      java.lang.Object ref = tStudentID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tStudentID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tStudentID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTStudentIDBytes() {
      java.lang.Object ref = tStudentID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tStudentID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tStudentID = 1;</code>
     */
    public Builder setTStudentID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tStudentID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tStudentID = 1;</code>
     */
    public Builder clearTStudentID() {
      
      tStudentID_ = getDefaultInstance().getTStudentID();
      onChanged();
      return this;
    }
    /**
     * <code>string tStudentID = 1;</code>
     */
    public Builder setTStudentIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tStudentID_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:getStudentAttendanceRequest)
  }

  // @@protoc_insertion_point(class_scope:getStudentAttendanceRequest)
  private static final com.smartClass.SCService1.getStudentAttendanceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smartClass.SCService1.getStudentAttendanceRequest();
  }

  public static com.smartClass.SCService1.getStudentAttendanceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<getStudentAttendanceRequest>
      PARSER = new com.google.protobuf.AbstractParser<getStudentAttendanceRequest>() {
    @java.lang.Override
    public getStudentAttendanceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new getStudentAttendanceRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<getStudentAttendanceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<getStudentAttendanceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smartClass.SCService1.getStudentAttendanceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

