// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SCService1.proto

package com.smartClass.SCService1;

public final class SCService1Impl {
  private SCService1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_setStudentAttendanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_setStudentAttendanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_setStudentAttendanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_setStudentAttendanceResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getStudentAttendanceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getStudentAttendanceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_getStudentAttendanceResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_getStudentAttendanceResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020SCService1.proto\"K\n\033setStudentAttendan" +
      "ceRequest\022\021\n\tstudentID\030\001 \001(\t\022\031\n\021studentR" +
      "FIDstatus\030\002 \001(\t\"N\n\034setStudentAttendanceR" +
      "esponse\022\030\n\020response_message\030\001 \001(\t\022\024\n\014res" +
      "ponseCode\030\002 \001(\005\"1\n\033getStudentAttendanceR" +
      "equest\022\022\n\ntStudentID\030\001 \001(\t\"a\n\034getStudent" +
      "AttendanceResponse\022\021\n\tstudentID\030\001 \001(\t\022\030\n" +
      "\020response_message\030\002 \001(\t\022\024\n\014responseCode\030" +
      "\003 \001(\0052\272\001\n\nSCService1\022U\n\024setStudentAttend" +
      "ance\022\034.setStudentAttendanceRequest\032\035.set" +
      "StudentAttendanceResponse\"\000\022U\n\024getStuden" +
      "tAttendance\022\034.getStudentAttendanceReques" +
      "t\032\035.getStudentAttendanceResponse\"\000B-\n\031co" +
      "m.smartClass.SCService1B\016SCService1ImplP" +
      "\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_setStudentAttendanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_setStudentAttendanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_setStudentAttendanceRequest_descriptor,
        new java.lang.String[] { "StudentID", "StudentRFIDstatus", });
    internal_static_setStudentAttendanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_setStudentAttendanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_setStudentAttendanceResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
    internal_static_getStudentAttendanceRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_getStudentAttendanceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getStudentAttendanceRequest_descriptor,
        new java.lang.String[] { "TStudentID", });
    internal_static_getStudentAttendanceResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_getStudentAttendanceResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_getStudentAttendanceResponse_descriptor,
        new java.lang.String[] { "StudentID", "ResponseMessage", "ResponseCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
