// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SCService1.proto

package com.smartClass.SCService1;

public interface setStudentAttendanceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:setStudentAttendanceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string studentID = 1;</code>
   */
  java.lang.String getStudentID();
  /**
   * <code>string studentID = 1;</code>
   */
  com.google.protobuf.ByteString
      getStudentIDBytes();

  /**
   * <code>string studentRFIDstatus = 2;</code>
   */
  java.lang.String getStudentRFIDstatus();
  /**
   * <code>string studentRFIDstatus = 2;</code>
   */
  com.google.protobuf.ByteString
      getStudentRFIDstatusBytes();
}
