// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SCService1.proto

package com.smartClass.SCService1;

/**
 * Protobuf type {@code setStudentAttendanceRequest}
 */
public  final class setStudentAttendanceRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:setStudentAttendanceRequest)
    setStudentAttendanceRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use setStudentAttendanceRequest.newBuilder() to construct.
  private setStudentAttendanceRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private setStudentAttendanceRequest() {
    studentID_ = "";
    studentRFIDstatus_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private setStudentAttendanceRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            studentID_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            studentRFIDstatus_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.smartClass.SCService1.SCService1Impl.internal_static_setStudentAttendanceRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.smartClass.SCService1.SCService1Impl.internal_static_setStudentAttendanceRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.smartClass.SCService1.setStudentAttendanceRequest.class, com.smartClass.SCService1.setStudentAttendanceRequest.Builder.class);
  }

  public static final int STUDENTID_FIELD_NUMBER = 1;
  private volatile java.lang.Object studentID_;
  /**
   * <code>string studentID = 1;</code>
   */
  public java.lang.String getStudentID() {
    java.lang.Object ref = studentID_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      studentID_ = s;
      return s;
    }
  }
  /**
   * <code>string studentID = 1;</code>
   */
  public com.google.protobuf.ByteString
      getStudentIDBytes() {
    java.lang.Object ref = studentID_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      studentID_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STUDENTRFIDSTATUS_FIELD_NUMBER = 2;
  private volatile java.lang.Object studentRFIDstatus_;
  /**
   * <code>string studentRFIDstatus = 2;</code>
   */
  public java.lang.String getStudentRFIDstatus() {
    java.lang.Object ref = studentRFIDstatus_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      studentRFIDstatus_ = s;
      return s;
    }
  }
  /**
   * <code>string studentRFIDstatus = 2;</code>
   */
  public com.google.protobuf.ByteString
      getStudentRFIDstatusBytes() {
    java.lang.Object ref = studentRFIDstatus_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      studentRFIDstatus_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getStudentIDBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, studentID_);
    }
    if (!getStudentRFIDstatusBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, studentRFIDstatus_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getStudentIDBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, studentID_);
    }
    if (!getStudentRFIDstatusBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, studentRFIDstatus_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.smartClass.SCService1.setStudentAttendanceRequest)) {
      return super.equals(obj);
    }
    com.smartClass.SCService1.setStudentAttendanceRequest other = (com.smartClass.SCService1.setStudentAttendanceRequest) obj;

    boolean result = true;
    result = result && getStudentID()
        .equals(other.getStudentID());
    result = result && getStudentRFIDstatus()
        .equals(other.getStudentRFIDstatus());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + STUDENTID_FIELD_NUMBER;
    hash = (53 * hash) + getStudentID().hashCode();
    hash = (37 * hash) + STUDENTRFIDSTATUS_FIELD_NUMBER;
    hash = (53 * hash) + getStudentRFIDstatus().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.smartClass.SCService1.setStudentAttendanceRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartClass.SCService1.setStudentAttendanceRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartClass.SCService1.setStudentAttendanceRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartClass.SCService1.setStudentAttendanceRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartClass.SCService1.setStudentAttendanceRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.smartClass.SCService1.setStudentAttendanceRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.smartClass.SCService1.setStudentAttendanceRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartClass.SCService1.setStudentAttendanceRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartClass.SCService1.setStudentAttendanceRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.smartClass.SCService1.setStudentAttendanceRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.smartClass.SCService1.setStudentAttendanceRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.smartClass.SCService1.setStudentAttendanceRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.smartClass.SCService1.setStudentAttendanceRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code setStudentAttendanceRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:setStudentAttendanceRequest)
      com.smartClass.SCService1.setStudentAttendanceRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.smartClass.SCService1.SCService1Impl.internal_static_setStudentAttendanceRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.smartClass.SCService1.SCService1Impl.internal_static_setStudentAttendanceRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.smartClass.SCService1.setStudentAttendanceRequest.class, com.smartClass.SCService1.setStudentAttendanceRequest.Builder.class);
    }

    // Construct using com.smartClass.SCService1.setStudentAttendanceRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      studentID_ = "";

      studentRFIDstatus_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.smartClass.SCService1.SCService1Impl.internal_static_setStudentAttendanceRequest_descriptor;
    }

    @java.lang.Override
    public com.smartClass.SCService1.setStudentAttendanceRequest getDefaultInstanceForType() {
      return com.smartClass.SCService1.setStudentAttendanceRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.smartClass.SCService1.setStudentAttendanceRequest build() {
      com.smartClass.SCService1.setStudentAttendanceRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.smartClass.SCService1.setStudentAttendanceRequest buildPartial() {
      com.smartClass.SCService1.setStudentAttendanceRequest result = new com.smartClass.SCService1.setStudentAttendanceRequest(this);
      result.studentID_ = studentID_;
      result.studentRFIDstatus_ = studentRFIDstatus_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.smartClass.SCService1.setStudentAttendanceRequest) {
        return mergeFrom((com.smartClass.SCService1.setStudentAttendanceRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.smartClass.SCService1.setStudentAttendanceRequest other) {
      if (other == com.smartClass.SCService1.setStudentAttendanceRequest.getDefaultInstance()) return this;
      if (!other.getStudentID().isEmpty()) {
        studentID_ = other.studentID_;
        onChanged();
      }
      if (!other.getStudentRFIDstatus().isEmpty()) {
        studentRFIDstatus_ = other.studentRFIDstatus_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.smartClass.SCService1.setStudentAttendanceRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.smartClass.SCService1.setStudentAttendanceRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object studentID_ = "";
    /**
     * <code>string studentID = 1;</code>
     */
    public java.lang.String getStudentID() {
      java.lang.Object ref = studentID_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studentID_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string studentID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStudentIDBytes() {
      java.lang.Object ref = studentID_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studentID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string studentID = 1;</code>
     */
    public Builder setStudentID(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      studentID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string studentID = 1;</code>
     */
    public Builder clearStudentID() {
      
      studentID_ = getDefaultInstance().getStudentID();
      onChanged();
      return this;
    }
    /**
     * <code>string studentID = 1;</code>
     */
    public Builder setStudentIDBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      studentID_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object studentRFIDstatus_ = "";
    /**
     * <code>string studentRFIDstatus = 2;</code>
     */
    public java.lang.String getStudentRFIDstatus() {
      java.lang.Object ref = studentRFIDstatus_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        studentRFIDstatus_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string studentRFIDstatus = 2;</code>
     */
    public com.google.protobuf.ByteString
        getStudentRFIDstatusBytes() {
      java.lang.Object ref = studentRFIDstatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        studentRFIDstatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string studentRFIDstatus = 2;</code>
     */
    public Builder setStudentRFIDstatus(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      studentRFIDstatus_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string studentRFIDstatus = 2;</code>
     */
    public Builder clearStudentRFIDstatus() {
      
      studentRFIDstatus_ = getDefaultInstance().getStudentRFIDstatus();
      onChanged();
      return this;
    }
    /**
     * <code>string studentRFIDstatus = 2;</code>
     */
    public Builder setStudentRFIDstatusBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      studentRFIDstatus_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:setStudentAttendanceRequest)
  }

  // @@protoc_insertion_point(class_scope:setStudentAttendanceRequest)
  private static final com.smartClass.SCService1.setStudentAttendanceRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.smartClass.SCService1.setStudentAttendanceRequest();
  }

  public static com.smartClass.SCService1.setStudentAttendanceRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<setStudentAttendanceRequest>
      PARSER = new com.google.protobuf.AbstractParser<setStudentAttendanceRequest>() {
    @java.lang.Override
    public setStudentAttendanceRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new setStudentAttendanceRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<setStudentAttendanceRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<setStudentAttendanceRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.smartClass.SCService1.setStudentAttendanceRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

