// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SCService1.proto

package com.smartClass.SCService1;

public interface setStudentAttendanceResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:setStudentAttendanceResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string response_message = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string response_message = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   */
  int getResponseCode();
}
